project_id        = "iac-epitech-dev"
region            = "europe-west1"
zone              = "europe-west1-b"
vpc_name          = "vpc"
cidr_block        = "10.0.0.0/16"
cluster_name      = "github-runner-cluster"
github_config_url = "https://github.com/tzhengtek/InfrastructureAsCode"
